version: '2'
services:
    reactjhipster-app:
        image: reactjhipster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://reactjhipster-mysql:3306/reactjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reactjhipster-mysql:
        extends:
            file: mysql.yml
            service: reactjhipster-mysql
